spring.application.name=Ecommerce Platform

# Conexion a PostgreSQL en Render (usar variables de entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/ADONAI_ECOMMERCE
spring.datasource.username=postgres
spring.datasource.password=Proverbios22:6_EL_4DM1N
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracion Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Credenciales temporales para desarrollo
spring.security.user.name=admin
spring.security.user.password=admin123

# Quitar warning de open-in-view
spring.jpa.open-in-view=false